site_name: Fiware-DataModels
site_url: https://fiware-datamodels.readthedocs.org
repo_url: https://github.com/fiware/dataModels.git
site_description: FIWARE Data Models Documentation
docs_dir: .
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - 'Home': index.md
  - 'Guidelines'  : guidelines.md
  - 'Alarms'                     : 'Alarm/doc/introduction.md'
  - 'Civic Issue Tracking':
      - 'Introduction'                 : 'IssueTracking/doc/introduction.md'
      - 'Open311:ServiceType'          : 'IssueTracking/Open311_ServiceType/doc/spec.md' 
      - 'Open311:ServiceRequest'       : 'IssueTracking/Open311_ServiceRequest/doc/spec.md'
  - 'Device':                           
      - 'Introduction'           : 'Device/doc/introduction.md'
      - 'Device'                 : 'Device/Device/doc/spec.md'
      - 'DeviceModel'            : 'Device/DeviceModel/doc/spec.md'
  - 'Environment':
      - 'Introduction'           : 'Environment/doc/introduction.md'
      - 'AirQualityObserved'     : 'Environment/AirQualityObserved/doc/spec.md'
      - 'AirQualityThreshold'    : 'Environment/AirQualityThreshold/doc/spec.md'
      - 'WaterQualityObserved'   : 'Environment/WaterQualityObserved/doc/spec.md'
  - 'Indicators':
      - 'KeyPerformanceIndicator' : 'KeyPerformanceIndicator/doc/spec.md'
  - 'Parking':
      - 'Introduction'         : 'Parking/doc/introduction.md' 
      - 'OffStreetParking'     : 'Parking/OffStreetParking/doc/spec.md'
      - 'OnStreetParking'      : 'Parking/OnStreetParking/doc/spec.md'
      - 'ParkingGroup'         : 'Parking/ParkingGroup/doc/spec.md'
      - 'ParkingAccess'        : 'Parking/ParkingAccess/doc/spec.md' 
      - 'ParkingSpot'          : 'Parking/ParkingSpot/doc/spec.md'
  - 'Parks & Gardens'          : 'ParksAndGardens/doc/introduction.md'          
  - 'Points of Interest': 
      - 'WeatherStation'       : 'PointOfInterest/WeatherStation/doc/spec.md'
      - 'AirQualityStation'    : 'PointOfInterest/AirQualityStation/doc/spec.md'
  -  'Street Lighting':
      - 'Introduction'              : 'StreetLighting/doc/introduction.md'
      - 'Streetlight'               : 'StreetLighting/Streetlight/doc/spec.md'
      - 'StreetlightModel'          : 'StreetLighting/StreetlightModel/doc/spec.md'
      - 'StreetlightGroup'          : 'StreetLighting/StreetlightGroup/doc/spec.md'
      - 'StreetlightControlCabinet' : 'StreetLighting/StreetlightControlCabinet/doc/spec.md'
  - 'Vehicle':
      - 'Introduction'         : 'Vehicle/doc/introduction.md'
      - 'Vehicle'              : 'Vehicle/Vehicle/doc/spec.md'
      - 'VehicleModel'         : 'Vehicle/VehicleModel/doc/spec.md'
  -  'Weather':
      - 'Introduction'         : 'Weather/doc/introduction.md'
      - 'WeatherObserved'      : 'Weather/WeatherObserved/doc/spec.md'
      - 'WeatherForecast'      : 'Weather/WeatherForecast/doc/spec.md'
      - 'WeatherAlarm'         : 'Weather/WeatherAlarm/doc/spec.md'
  -  'Waste Management':
      - 'Introduction'         : 'WasteManagement/doc/introduction.md'
      - 'WasteContainerIsle'   : 'WasteManagement/WasteContainerIsle/doc/spec.md'
      - 'WasteContainerModel'  : 'WasteManagement/WasteContainerModel/doc/spec.md'
      - 'WasteContainer'       : 'WasteManagement/WasteContainer/doc/spec.md'

google_analytics: ['UA-83719923-1', 'fiware-datamodels.readthedocs.io']
